version: '3'

services:
  base:
    image: 'datadog/dd-trace-ci:centos-6'
    build:
      context: .

  php-5.5:
    build:
      context: ./php-5.5
    image: 'datadog/dd-trace-ci:php-5.5_centos-6'

  php-7.0:
    build:
      context: ./php-7.0
      args:
        phpVersion: 7.0
        phpTarGzUrl: https://www.php.net/distributions/php-7.0.33.tar.gz
        phpSha256Hash: d71a6ecb6b13dc53fed7532a7f8f949c4044806f067502f8fb6f9facbb40452a
    image: 'datadog/dd-trace-ci:php-7.0_centos-6'

  php-8.0:
    build:
      context: ./php-8.0
      args:
        phpVersion: 8.0
        phpTarGzUrl: https://www.php.net/distributions/php-8.0.0.tar.gz
        phpSha256Hash: 3ed7b48d64357d3e8fa9e828dbe7416228f84105b8290c2f9779cd66be31ea71
    image: 'datadog/dd-trace-ci:php-8.0_centos-6'
